apiVersion: v1
kind: Namespace
metadata:
  name: sales-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales # name of the pod
  namespace: sales-system # the name space where this pod will be created
spec:
  selector:
    matchLabels:
      app: sales # labels let kubectl query with -l
  replicas: 1 # staging and production will probably have more than 1, but dev has 1
  strategy:
    type: Recreate # specific to dev environment
  template:
    metadata:
      labels:
        app: sales
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: sales-api
          resources:
            limits:
              cpu: "2000m" # Up to 2 full cores
            requests:
              cpu: "1000m" # Use 1 full core
---
apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: sales-system
spec:
  selector:
    app: sales
  type: ClusterIP
  ports: # ports on a service are "outside" ports
    - name: sales-api
      port: 3000
      targetPort: sales-api # they match to "inside" ports on a deployment.
    - name: sales-api-debug
      port: 4000
      targetPort: sales-api-debug
