apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/sales/ # use the resources in the base manifest
patchesStrategicMerge:
- ./dev-sales-patch.yaml # add the patch by strategic merge
images:
- name: sales-api-image # replace this name in base manifest
  newName: sales-api
  newTag: "1.0"